/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VIsta;

/**
 *
 * @author bryan
 */
public class FormProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormProducto
     */
    public FormProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jtxtIdCategoria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxtNombreProd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtStock = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtPrecio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtIdProducto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbtnRegistrar = new javax.swing.JButton();
        jbtnBorar = new javax.swing.JButton();
        jtxtBuscarTXT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jbtnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblDatos = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1220, 622));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jtxtIdCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 140, 30));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("ID Categoría:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 140, 30));
        jPanel2.add(jtxtNombreProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 240, 40));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Nombre");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        jPanel2.add(jtxtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 240, 40));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Stock");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));
        jPanel2.add(jtxtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 240, 40));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Precio");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));
        jPanel2.add(jtxtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 140, 30));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("ID Producto:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 30));

        jbtnRegistrar.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jbtnRegistrar.setText("REGISTRAR");
        jPanel2.add(jbtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 110, 40));

        jbtnBorar.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jbtnBorar.setText("BORRAR");
        jPanel2.add(jbtnBorar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 110, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 490));

        jtxtBuscarTXT.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        getContentPane().add(jtxtBuscarTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 50, 200, 30));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setText("LISTA DE PRODUCTOS");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        jbtnBuscar.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jbtnBuscar.setText("BUSCAR");
        getContentPane().add(jbtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 50, 110, 30));

        jtblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 870, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtnBorar;
    public javax.swing.JButton jbtnBuscar;
    public javax.swing.JButton jbtnRegistrar;
    public javax.swing.JTable jtblDatos;
    public javax.swing.JTextField jtxtBuscarTXT;
    public javax.swing.JTextField jtxtIdCategoria;
    public javax.swing.JTextField jtxtIdProducto;
    public javax.swing.JTextField jtxtNombreProd;
    public javax.swing.JTextField jtxtPrecio;
    public javax.swing.JTextField jtxtStock;
    // End of variables declaration//GEN-END:variables
}
